In [1]:
import pandas as pd

df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [3]:
df['spam'] = df['Category'].apply(lambda x : 1 if x == 'spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df.Message , df.spam , test_size = 0.25)
X_train[:4]

697     Aight, you close by or still down around alex'...
720     Macha dont feel upset.i can assume your mindse...
473     Nothing. I meant that once the money enters yo...
3261    I'm always looking for an excuse to be in the ...
Name: Message, dtype: object

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train_count = vectorizer.fit_transform(X_train)
X_test_count = vectorizer.transform(X_test)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
y_train

697     0
720     0
473     0
3261    0
2465    0
       ..
4255    0
3066    0
375     1
4834    1
41      0
Name: spam, Length: 4179, dtype: int64

In [40]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [45]:
# model.score(X_test_count,y_test)
emails = ['I HAVE A DATE ON SUNDAY WITH WILL!!',
        'XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL',
         'Please call our customer service representative']
emails_count = vectorizer.transform(emails)
model.predict(emails_count)

array([0, 1, 1])

In [46]:
model.score(X_test_count , y_test)

0.9863603732950467

In [53]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('Vectorizer' , CountVectorizer()),
    ('nb' , MultinomialNB())
    
])

In [54]:
clf.fit(X_train,y_train)

Pipeline(steps=[('Vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [55]:
clf.predict(emails)

array([0, 1, 1])

In [56]:
clf.score(X_test , y_test)

0.9863603732950467

In [64]:
clf.predict(['Am I Spam?' , 'Yes I am if any doubt please call our customer service representative'])

array([0, 1])