In [11]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math
url = "https://raw.githubusercontent.com/SahruzRiyad/Machine-Learing-Basic/main/House.csv"
dataset = pd.read_csv(url)
dataset

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [12]:
median_bedrooms = math.floor(dataset.bedrooms.median())
median_bedrooms

3

In [13]:
dataset.bedrooms = dataset.bedrooms.fillna(median_bedrooms)
dataset

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [15]:
reg = linear_model.LinearRegression()
reg.fit(dataset[['area','bedrooms','age']], dataset.price)

LinearRegression()

In [18]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [22]:
reg.predict([[2600,2,30]])

array([483775.])

In [24]:
reg.predict([[2500,4,5]])

array([588625.])